#!/usr/bin/env python3
"""Generate the KeyMint name tables the logs decode with, from the AIDL itself.

Reads Tag, ErrorCode and the enums a tag's value can hold from
third_party/interfaces/security/keymint/aidl, and writes:

  common/km_names_gen.inc                          C++ tables for common/km_names.cpp
  app/src/main/java/org/matrix/teesim/KmAidl.kt    the same tables for the daemon

Both outputs are checked in; rerun this after the interfaces submodule moves. It fails if an
ENUM or ENUM_REP tag has no enum assigned below, so a new enum-valued tag cannot slip into the
logs as a bare number unnoticed.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AIDL = ROOT / "third_party/interfaces/security/keymint/aidl/android/hardware/security/keymint"
CPP_OUT = ROOT / "common/km_names_gen.inc"
KT_OUT = ROOT / "app/src/main/java/org/matrix/teesim/KmAidl.kt"

# The enums a tag's value is decoded through. USER_AUTH_TYPE is a bitmask of its enum's members.
ENUMS = [
    "Algorithm",
    "BlockMode",
    "Digest",
    "EcCurve",
    "HardwareAuthenticatorType",
    "KeyFormat",
    "KeyOrigin",
    "KeyPurpose",
    "MlDsaVariant",
    "PaddingMode",
    "SecurityLevel",
]
TAG_ENUM = {
    "PURPOSE": "KeyPurpose",
    "ALGORITHM": "Algorithm",
    "BLOCK_MODE": "BlockMode",
    "DIGEST": "Digest",
    "PADDING": "PaddingMode",
    "EC_CURVE": "EcCurve",
    "ML_DSA_VARIANT": "MlDsaVariant",
    "RSA_OAEP_MGF_DIGEST": "Digest",
    "HARDWARE_TYPE": "SecurityLevel",
    "USER_AUTH_TYPE": "HardwareAuthenticatorType",
    "ORIGIN": "KeyOrigin",
}

TAG_TYPES = {}


def members(name):
    """(NAME, value) pairs of an AIDL enum, in declaration order."""
    text = (AIDL / f"{name}.aidl").read_text()
    body = text[re.search(r"\benum\s+\w+\s*\{", text).end() : text.rindex("}")]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    out = []
    for m in re.finditer(r"([A-Z][A-Z0-9_]*)\s*=\s*([^,]+),?", body):
        expr = m.group(2).strip()
        expr = re.sub(r"TagType\.([A-Z_]+)", lambda t: str(TAG_TYPES[t.group(1)]), expr)
        value = eval(expr, {"__builtins__": {}})  # integer literals, <<, | and unary minus only
        out.append((m.group(1), value))
    return out


def snake(name):
    """KeyPurpose -> KEY_PURPOSE."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def s32(v):
    return v - (1 << 32) if v >= (1 << 31) else v


def main():
    TAG_TYPES.update(members("TagType"))
    tags = [(n, v) for n, v in members("Tag") if v != 0]
    enums = {e: members(e) for e in ENUMS}
    errors = members("ErrorCode")

    enum_tags = [n for n, v in tags if (v >> 28) in (TAG_TYPES["ENUM"] >> 28, TAG_TYPES["ENUM_REP"] >> 28)]
    missing = [n for n in enum_tags if n not in TAG_ENUM]
    if missing:
        sys.exit(f"gen-km-names: no enum assigned for tag(s) {', '.join(missing)}; add them to TAG_ENUM")

    enum_ids = {e: i for i, e in enumerate(ENUMS)}
    header = "Generated by scripts/gen-km-names.py from the KeyMint AIDL. Do not edit."

    cpp = [f"// {header}", ""]
    cpp.append("enum KmEnumId : int8_t {")
    cpp += [f"  kEnum{e} = {i}," for e, i in enum_ids.items()]
    cpp += ["  kEnumNone = -1,", "};", ""]
    for e in ENUMS:
        cpp.append(f"constexpr KmName k{e}[] = {{")
        cpp += [f'    {{{s32(v)}, "{n}"}},' for n, v in enums[e]]
        cpp.append("};")
    cpp.append("")
    cpp.append("constexpr KmEnumTable kEnumTables[] = {")
    cpp += [f"    {{k{e}, sizeof(k{e}) / sizeof(k{e}[0])}}," for e in ENUMS]
    cpp += ["};", ""]
    cpp.append("constexpr KmTagEntry kTags[] = {")
    for n, v in tags:
        e = TAG_ENUM.get(n)
        cpp.append(f'    {{0x{v:08x}u, "{n.lower()}", {f"kEnum{e}" if e else "kEnumNone"}}},')
    cpp += ["};", ""]
    cpp.append("constexpr KmName kErrors[] = {")
    cpp += [f'    {{{v}, "{n}"}},' for n, v in errors]
    cpp.append("};")
    CPP_OUT.write_text("\n".join(cpp) + "\n")

    def kt_map(name, pairs, key=lambda v: v):
        lines = [f"    val {name}: Map<Long, String> ="]
        lines.append("        mapOf(")
        lines += [f'            {key(v)}L to "{n}",' for n, v in pairs]
        lines.append("        )")
        return lines

    kt = ["package org.matrix.teesim", "", f"// {header}", ""]
    kt += [
        "/** KeyMint AIDL names: tags by their number (the low 28 bits), and each value enum. */",
        "object KmAidl {",
    ]
    kt += kt_map("TAG", [(n.lower(), v & 0x0FFFFFFF) for n, v in tags])
    kt.append("")
    date = TAG_TYPES["DATE"]
    kt.append("    /** Tag numbers whose value is a date (milliseconds since the epoch). */")
    kt.append("    val DATE_TAGS: Set<Long> =")
    kt.append("        setOf(")
    kt += [f"            {v & 0x0FFFFFFF}L," for n, v in tags if (v & 0xF0000000) == date]
    kt += ["        )", ""]
    kt.append("    /** The enum a tag number's value decodes through, by tag number. */")
    kt.append("    val TAG_ENUM: Map<Long, Map<Long, String>> by lazy {")
    kt.append("        mapOf(")
    for n, v in tags:
        if n in TAG_ENUM:
            kt.append(f"            {v & 0x0FFFFFFF}L to {snake(TAG_ENUM[n])},")
    kt += ["        )", "    }"]
    for e in ENUMS:
        kt.append("")
        kt += kt_map(snake(e), enums[e], key=lambda v: s32(v))
    kt.append("}")
    KT_OUT.write_text("\n".join(kt) + "\n")
    print(f"wrote {CPP_OUT.relative_to(ROOT)} and {KT_OUT.relative_to(ROOT)}: "
          f"{len(tags)} tags, {len(ENUMS)} enums, {len(errors)} error codes")


if __name__ == "__main__":
    main()
