package org.matrix.teesim

// Generated by scripts/gen-km-names.py from the KeyMint AIDL. Do not edit.

/** KeyMint AIDL names: tags by their number (the low 28 bits), and each value enum. */
object KmAidl {
    val TAG: Map<Long, String> =
        mapOf(
            1L to "purpose",
            2L to "algorithm",
            3L to "key_size",
            4L to "block_mode",
            5L to "digest",
            6L to "padding",
            7L to "caller_nonce",
            8L to "min_mac_length",
            10L to "ec_curve",
            11L to "ml_dsa_variant",
            200L to "rsa_public_exponent",
            202L to "include_unique_id",
            203L to "rsa_oaep_mgf_digest",
            302L to "bootloader_only",
            303L to "rollback_resistance",
            304L to "hardware_type",
            305L to "early_boot_only",
            400L to "active_datetime",
            401L to "origination_expire_datetime",
            402L to "usage_expire_datetime",
            403L to "min_seconds_between_ops",
            404L to "max_uses_per_boot",
            405L to "usage_count_limit",
            501L to "user_id",
            502L to "user_secure_id",
            503L to "no_auth_required",
            504L to "user_auth_type",
            505L to "auth_timeout",
            506L to "allow_while_on_body",
            507L to "trusted_user_presence_required",
            508L to "trusted_confirmation_required",
            509L to "unlocked_device_required",
            601L to "application_id",
            700L to "application_data",
            701L to "creation_datetime",
            702L to "origin",
            704L to "root_of_trust",
            705L to "os_version",
            706L to "os_patchlevel",
            707L to "unique_id",
            708L to "attestation_challenge",
            709L to "attestation_application_id",
            710L to "attestation_id_brand",
            711L to "attestation_id_device",
            712L to "attestation_id_product",
            713L to "attestation_id_serial",
            714L to "attestation_id_imei",
            715L to "attestation_id_meid",
            716L to "attestation_id_manufacturer",
            717L to "attestation_id_model",
            718L to "vendor_patchlevel",
            719L to "boot_patchlevel",
            720L to "device_unique_attestation",
            721L to "identity_credential_key",
            722L to "storage_key",
            723L to "attestation_id_second_imei",
            724L to "module_hash",
            1000L to "associated_data",
            1001L to "nonce",
            1003L to "mac_length",
            1004L to "reset_since_id_rotation",
            1005L to "confirmation_token",
            1006L to "certificate_serial",
            1007L to "certificate_subject",
            1008L to "certificate_not_before",
            1009L to "certificate_not_after",
            1010L to "max_boot_level",
        )

    /** Tag numbers whose value is a date (milliseconds since the epoch). */
    val DATE_TAGS: Set<Long> =
        setOf(
            400L,
            401L,
            402L,
            701L,
            1008L,
            1009L,
        )

    /** The enum a tag number's value decodes through, by tag number. */
    val TAG_ENUM: Map<Long, Map<Long, String>> by lazy {
        mapOf(
            1L to KEY_PURPOSE,
            2L to ALGORITHM,
            4L to BLOCK_MODE,
            5L to DIGEST,
            6L to PADDING_MODE,
            10L to EC_CURVE,
            11L to ML_DSA_VARIANT,
            203L to DIGEST,
            304L to SECURITY_LEVEL,
            504L to HARDWARE_AUTHENTICATOR_TYPE,
            702L to KEY_ORIGIN,
        )
    }

    val ALGORITHM: Map<Long, String> =
        mapOf(
            1L to "RSA",
            3L to "EC",
            4L to "ML_DSA",
            32L to "AES",
            33L to "TRIPLE_DES",
            128L to "HMAC",
        )

    val BLOCK_MODE: Map<Long, String> =
        mapOf(
            1L to "ECB",
            2L to "CBC",
            3L to "CTR",
            32L to "GCM",
        )

    val DIGEST: Map<Long, String> =
        mapOf(
            0L to "NONE",
            1L to "MD5",
            2L to "SHA1",
            3L to "SHA_2_224",
            4L to "SHA_2_256",
            5L to "SHA_2_384",
            6L to "SHA_2_512",
        )

    val EC_CURVE: Map<Long, String> =
        mapOf(
            0L to "P_224",
            1L to "P_256",
            2L to "P_384",
            3L to "P_521",
            4L to "CURVE_25519",
        )

    val HARDWARE_AUTHENTICATOR_TYPE: Map<Long, String> =
        mapOf(
            0L to "NONE",
            1L to "PASSWORD",
            2L to "FINGERPRINT",
            -1L to "ANY",
        )

    val KEY_FORMAT: Map<Long, String> =
        mapOf(
            0L to "X509",
            1L to "PKCS8",
            3L to "RAW",
        )

    val KEY_ORIGIN: Map<Long, String> =
        mapOf(
            0L to "GENERATED",
            1L to "DERIVED",
            2L to "IMPORTED",
            3L to "RESERVED",
            4L to "SECURELY_IMPORTED",
        )

    val KEY_PURPOSE: Map<Long, String> =
        mapOf(
            0L to "ENCRYPT",
            1L to "DECRYPT",
            2L to "SIGN",
            3L to "VERIFY",
            5L to "WRAP_KEY",
            6L to "AGREE_KEY",
            7L to "ATTEST_KEY",
        )

    val ML_DSA_VARIANT: Map<Long, String> =
        mapOf(
            1L to "ML_DSA_65",
            2L to "ML_DSA_87",
        )

    val PADDING_MODE: Map<Long, String> =
        mapOf(
            1L to "NONE",
            2L to "RSA_OAEP",
            3L to "RSA_PSS",
            4L to "RSA_PKCS1_1_5_ENCRYPT",
            5L to "RSA_PKCS1_1_5_SIGN",
            64L to "PKCS7",
        )

    val SECURITY_LEVEL: Map<Long, String> =
        mapOf(
            0L to "SOFTWARE",
            1L to "TRUSTED_ENVIRONMENT",
            2L to "STRONGBOX",
            100L to "KEYSTORE",
        )
}
